//! Raw FFI bindings for Hailo's HailoRT C library.
//!
//! Generated by `build.rs` via `bindgen` against `<hailo/hailort.h>` when
//! the `hailo` feature is enabled. Without the feature this is an empty
//! stub so `cargo check` works on hosts without HailoRT installed.
//!
//! ADR-167 §5 step 3 (`hailo-backend` branch).

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::missing_safety_doc)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/// Smoke-test reachability of the bound library by calling
/// `hailo_get_library_version`. Validates that bindgen produced usable
/// FFI signatures *and* the linker actually resolved `libhailort.so`.
///
/// Returns `Ok((major, minor, revision))` on a Pi 5 + AI HAT+ build with
/// the `hailo` feature. Without the feature, returns `Ok((0, 0, 0))` to
/// signal "feature disabled" without a separate error path.
pub fn version_triple() -> Option<(u32, u32, u32)> {
    #[cfg(feature = "hailo")]
    {
        // SAFETY: `hailo_get_library_version` writes a `hailo_version_t`
        // through the supplied pointer and returns a `hailo_status` (0 on
        // success). We pass a freshly-zeroed struct on the stack and read
        // it back only if the status is success.
        unsafe {
            let mut v: hailo_version_t = std::mem::zeroed();
            let status = hailo_get_library_version(&mut v as *mut _);
            if status == 0 {
                Some((v.major as u32, v.minor as u32, v.revision as u32))
            } else {
                None
            }
        }
    }
    #[cfg(not(feature = "hailo"))]
    {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[cfg(not(feature = "hailo"))]
    #[test]
    fn stub_returns_none_without_feature() {
        assert_eq!(version_triple(), None);
    }

    #[cfg(feature = "hailo")]
    #[test]
    fn version_triple_matches_runtime() {
        let v = version_triple().expect("with `hailo` feature, version must be Some");
        // HailoRT 4.23.0 ships on the Pi 5 AI HAT+ as of 2026-05.
        // Major must be at least 4. Minor and revision are version-dependent.
        assert!(v.0 >= 4, "HailoRT major version {} unexpectedly low", v.0);
        eprintln!("HailoRT version: {}.{}.{}", v.0, v.1, v.2);
    }
}
